### ISSUE TITLE
How to handle multiple Repository transactions

### ISSUE THREAD

**Issue by OC0311** [bxcodec/go-clean-arch#59] opened 2021-04-07 01:50 UTC
I have read your article and code to help me a lot, but I have a question, do not know how to solve, when a business needs multiple Repository cooperation, and they are a transaction, how to deal with such a situation? And this is the majority of cases, can you add similar examples in the code?

**Comment by mcwienczek** [comment] 2021-04-25 20:11
isn't that a duplicate of https://github.com/bxcodec/go-clean-arch/issues/45 ?

**Comment by bxcodec** [comment] 2022-08-04 01:11
duplicated by #45 
closing this, refer to #36(PR) for future transactions related

**Closed by bxcodec** 2022-08-04 01:11 UTC
